version: '3.9'

services:
  web:
    build: .
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654zz321xx
      POSTGRES_DB: scraper_data
      # POSTGRES_HOST_AUTH_METHOD: trust  # Set authentication method to trust to allow connections without a password
      # PGSSLMODE: require  # Enable SSL for the PostgreSQL connection
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ssl:/ssl  # Mount the directory containing SSL certificates
    command: postgres -c ssl_cert_file=/ssl/server.crt -c ssl_key_file=/ssl/server.key

volumes:
  pgdata:
